### ISSUE TITLE
Submitting array job with sudo fails.

### ISSUE THREAD

**Issue by chebee7i** [gridengine/drmaa2-python#6]
Hi, I'm having some trouble using the `Sudo` object with `run_bulk_jobs`.

Here's an example that works, but using run_job instead.

```python
from drmaa2 import JobSession
from drmaa2 import JobTemplate
from drmaa2 import Sudo

if __name__ == '__main__':
    auth = Sudo(username='chebee7i')
    js = JobSession()
    d = {
        'remote_command': '/bin/bash',
        'args': ['-c', 'echo hi'],
        'implementation_specific': {
            'uge_jt_native': '-w e -l h_rt=100000:00:00,estmem=51539605552.0,h_vmem=72.000G',
        },
    }
    print('Running job using dictionary: %s' % d)
    j = js.run_job(d, auth)
    print('Submitted job: %s' % j)
```

If I change that submission line to:
```python
    j = js.run_bulk_jobs(d, 1, 10, 2, 2, auth=auth)
```
then I get a failure:
```console
2021-11-16 23:20:42,913 DEBUG job_session.py:314:  Using sudo object: {'username': 'chebee7i'}
Traceback (most recent call last):
  File "lala.py", line 20, in <module>
    j = js.run_bulk_jobs(d, 1, 10, 2, 2, auth=auth)
  File "/path/to/site-packages/drmaa2-python/drmaa2/job_session.py", line 321, in run_bulk_jobs
    self.exception_mapper.check_last_error_code()
  File "/path/to/site-packages/drmaa2-python/drmaa2/exception_mapper.py", line 98, in check_last_error_code
    cls.check_status_code(code)
  File "/path/to/site-packages/drmaa2-python/drmaa2/exception_mapper.py", line 111, in check_status_code
    raise error
drmaa2.drmaa2_exceptions.InvalidArgument: Values too large for DRM.
```
Similarly, running `run_bulk_jobs` without `auth` works fine.

Any tips? Running `Univa Grid Engine Drmaa V2`, `8.6.17`.

**Comment by mdonauer** [comment]
I added a fix to get the run bulk as working with sudo.
Internal tests have shown it as working.

**Comment by mdonauer** [comment]
User confirmed, changes are wokrking.
Checked in to V86 and master branch.
Issue can be closed.

Regards,
Marco
